version: 0.2

phases:
  pre_build:
    commands:
      - echo Build test started on `date`
  build:
    commands:
      - mvn test
  post_build:
    commands:
      - echo Build started on `date`
      - mvn package
    finally:
      - echo Build completed on `date`
artifacts:
  files:
    - '*-0.0.1-SNAPSHOT.jar'
  base-directory: 'target/'