spring.profiles.active=dev
springdoc.api-docs.path=/swagger
spring.datasource.url=jdbc:postgresql://localhost:5432/nxgdb
spring.datasource.username=nxg
spring.datasource.password=nxgpassword
<<<<<<< HEAD
=======
server.port=8082
>>>>>>> 395deb7 (controllers updated)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update


spring.security.user.name=dev
spring.security.user.password=dev
spring.security.user.roles=USER,ADMIN
logging.level.org.springframework=info
<<<<<<< HEAD
server.max-http-request-header-size = 10000000 
=======
server.max-http-request-header-size =10000000
>>>>>>> 395deb7 (controllers updated)
