package core.nxg.utils.constants;

public class EmailConstant {

    public static final String PASSWORD_RESET_CONTENT = "<html>"
    + "<br> Dear [[name]],<br>"
    + "<head>"
    + "<style>"
    + "body {"
    + "  font-family: Arial, Helvetica, sans-serif;"
    + "  font-size: 1rem;"
    + "  line-height: 1.6;"
    + "  color: #000;"
    + "}"
    + "</style>"
    + "</head>"
    + "<body style=\"text-align: center;\">"
    + " <div style=\"margin: 0 auto; width: 50%;\">"
    + "   <h1 style=\"font-weight: bold;\">Reset Your Password!</h1>"
    + "   <p>Your request to <strong>Reset your password!</strong> To get started, please click the button.</p>"
    + "   <a href=\"[[URL]]\" style=\"text-decoration: none;\">"
    + "     <button style=\"background-color: #007BFF; color: #fff; font-weight: bold; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer; transition: background-color 0.3s;\">Reset Password</button>"
    + "   </a>"
    + " </div>"
    + " <p style=\"margin-top: 50px;\">If you did not make this request please report this incident.</p>"
    + " <p>Thanks,</p>"
    + " <p style=\"font-weight: bold;\">The NXG-JOB HUB Team</p>"
    + "</body>"
    + "</html>";

    public static final String VERIFICATION_EMAIL_CONTENT = "<html><head><style>"
            + "body {font-family: Arial, Helvetica, sans-serif; font-size: 1rem; line-height: 1.6; color: #000; margin: 0; padding: 0; background-color: #f4f4f4; text-align: center;}"
            + ".container {margin: 0 auto; width: 50%; background-color: #ffffff; padding: 20px; border-radius: 8px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); text-align: center;}"
            + "h1, p {text-align: center;}"
            + "h1 {color: #333; font-weight: bold;}"
            + ".button { display: inline-block; background-color: #007BFF; color: #fff; font-weight: bold; padding: 10px 10px; text-decoration: none; border-radius: 5px; border: none; cursor: pointer; transition: background-color 0.3s; }"
            + ".button:hover {background-color: #0056b3;}"
            + ".footer {margin-top: 20px;}"
            + ".salutation {text-align: left; margin-left: 5%;}"
            + "</style></head><body><div class=\"container\">"
            + "<img src=\"data:image/png;base64,{{logo}}\" alt=\"NXG-JOB HUB Logo\" style=\"max-width: 100%; height: auto;\">"
            + "<h1>Verify Your Email Address</h1>"
            + "<p class=\"salutation\">Dear[[name]],</p>"
            + "<p>Welcome to <strong>NXG-JOB HUB</strong>! To get started, please click the button below to verify your email address.</p>"
            + "<a style=\" color: white; \" href=\"[[URL]]\" class=\"button\">Verify Your Email</a>"
            + "<p class=\"footer\"><strong>This email expires in 24 hrs. If you did not create an account using this address, please ignore it.</strong></p>"
            + "<p>Thanks,</p>"
            + "<p><strong>The NXG-JOB HUB Team</strong></p>"
            + "</div></body></html>";


    public static final String JOBPOSTING_NOTIFICATION_CONTENT ="<!DOCTYPE html>"
            + "<html><head><style>"
            + "body {font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; font-size: 16px; line-height: 1.6; color: #333; margin: 0; padding: 0; background-color: #f9f9f9;}"
            + ".container {width: 90%; max-width: 600px; margin: 40px auto; background-color: #fff; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);}"
            + ".container h1, .container h2 {color: #007BFF; margin-bottom: 20px;}"
            + ".container p {margin-bottom: 20px; text-align: left;}"
            + ".button {display: inline-block; background-color: #007BFF; color: #fff; font-weight: bold; padding: 15px 25px; text-decoration: none; border-radius: 5px; transition: background-color 0.3s;}"
            + ".button:hover {background-color: #0056b3;}"
            + ".footer {margin-top: 30px; text-align: center; color: #555;}"
            + "</style></head><body>"
            + "<div class=\"container\">"
            + "<h1>New Job Posting at NXG-JOB HUB</h1>"
            + "<p>Dear[[name]],</p>"
            + "<p>We are excited to inform you about a new job posting that might interest you.</p>"
            + "<h2>[[job_title]]</h2>"
            + "<p><strong>Company:</strong> [[company_bio]]</p>"
            + "<p><strong>Location:</strong> [[job_location]]</p>"
            + "<p><strong>Job Description:</strong></p>"
            + "<p style=\"text-indent: 50px;\">[[job_description]]</p>"
            + "<p>For more details and to apply, please click the button below.</p>"
            + "<a href=\"[[jobURL]]\" class=\"button\">Apply Now</a>"
            + "<div class=\"footer\">"
            + "<p>If you have any questions, please feel free to contact us.</p>"
            + "<p>Thanks,</p>"
            + "<p><strong>The NXG-JOB HUB Team</strong></p>"
            + "</div></div>"
            + "</body></html>";
        public static final String OAUTH_MAIL_CONTENT = "<html >"
            + "<head>"
            + "<style>"
            + "body {"
            + "  font-family: Arial, Helvetica, sans-serif;"
            + "  font-size: 1rem;"
            + "  line-height: 1.6;"
            + "  color: #000;"
            + "}"
            + "</style>"
            + "</head>"
            + "<body style=\"text-align:justify;\">"
            + "  <h1 style=\"font-weight: bold;\">NXGJOBHUB OAUTH LOGIN DETAILS</h1>"
            + "   <p>Dear [[name]],</p>"
            + "   <p>Please find below your Login Details:</p>"
            + "   <p>Email: [[email]]</p>"
            + "   <p>Password: [[password]]</p>"
            + "   <p style=\"margin-top: 50px;\">If you have any questions, please feel free to contact us.</p>"
            + "   <p>Thanks,</p>"
            + "   <p style=\"font-weight: bold;\">The NXG-JOB HUB Team</p>"
            + "</body>"
            + "</html>";


    public static final String HEADER_SIGNATURE_DELIVERY_CONTENT = "<html>"
            + "<head>"
            + "<style>"
            + "body {"
            + "  font-family: Arial, Helvetica, sans-serif;"
            + "  font-size: 1rem;"
            + "  line-height: 1.6;"
            + "  color: #333;"
            + "  background-color: #f4f4f4;"
            + "  padding: 20px;"
            + "}"
            + ".container {"
            + "  background-color: #fff;"
            + "  border-radius: 5px;"
            + "  padding: 20px;"
            + "  margin: 0 auto;"
            + "  width: 80%;"
            + "}"
            + ".header {"
            + "  text-align: center;"
            + "  padding: 10px 0;"
            + "  border-bottom: 1px solid #ddd;"
            + "}"
            + ".header h1 {"
            + "  font-size: 2rem;"
            + "  color: #007BFF;"
            + "}"
            + ".content {"
            + "  margin-top: 20px;"
            + "}"
            + ".footer {"
            + "  margin-top: 30px;"
            + "  text-align: center;"
            + "  color: #888;"
            + "}"
            + "</style>"
            + "</head>"
            + "<body>"
            + " <div class=\"container\">"
            + "   <div class=\"header\">"
            + "     <h1>New Header Signature Generated</h1>"
            + "   </div>"
            + "   <div class=\"content\">"
            + "     <p>Dear Tester ,</p>"
            + "     <p>We have generated a new header signature for your account. This signature is used to secure your communications with our server.</p>"
            + "     <p><strong>Header Signature 1:</strong> [[header_signature_ONE]]</p>"
            + "     <p><strong>Header Signature 2:</strong> [[header_signature_TWO]]</p>"
            + "     <p><strong>Header Signature 3:</strong> [[header_signature_THREE]]</p>"
            + "     <p>Please update your application with this new header signature. If you have any questions or need assistance, please contact our support team.</p>"
            + "     <p>Securing your header signatures is crucial to protect your data and prevent unauthorized access to your account. A strong, unique header signature helps ensure that your communications with our server are secure and trusted.</p>"
            + "   </div>"
            + "   <div class=\"footer\">"
            + "     <p>Thanks,</p>"
            + "     <p>The NXT-JOB HUB Team</p>"
            + "   </div>"
            + " </div>"
            + "</body>"
            + "</html>";
}

