package core.nxg.utils.constants;

public class EmailConstant {

    public static final String PASSWORD_RESET_CONTENT = "<html>"
    + "<br> Dear [[name]],<br>"
    + "<head>"
    + "<style>"
    + "body {"
    + "  font-family: Arial, Helvetica, sans-serif;"
    + "  font-size: 1rem;"
    + "  line-height: 1.6;"
    + "  color: #000;"
    + "}"
    + "</style>"
    + "</head>"
    + "<body style=\"text-align: center;\">"
    + " <div style=\"margin: 0 auto; width: 50%;\">"
    + "   <h1 style=\"font-weight: bold;\">Reset Your Password!</h1>"
    + "   <p>Your request to <strong>Reset your password!</strong> To get started, please click the button.</p>"
    + "   <a href=\"[[URL]]\" style=\"text-decoration: none;\">"
    + "     <button style=\"background-color: #007BFF; color: #fff; font-weight: bold; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer; transition: background-color 0.3s;\">Reset Password</button>"
    + "   </a>"
    + " </div>"
    + " <p style=\"margin-top: 50px;\">If you did not make this request please report this incident.</p>"
    + " <p>Thanks,</p>"
    + " <p style=\"font-weight: bold;\">The NXG-JOB HUB Team</p>"
    + "</body>"
    + "</html>";

    public static final String VERIFICATION_EMAIL_CONTENT = "<html lang=\"en\" xmlns:th=\"http://www.thymeleaf.org\">"
    + "<br> Dear [[name]],<br>"
    + "<head >"
    + "<style>"
    + "body {"
    + "  font-family: Arial, Helvetica, sans-serif;"
    + "  font-size: 1rem;"
    + "  line-height: 1.6;"
    + "  color: #000;"
    + "  background-image: url(cid:${mylogo});"
     + "  background-image: [[my_logo]]"

    + "  background-repeat: no-repeat;"
    + "  background-size: cover;"
    + "}"
            + "<img src =cid:${mylogo} />"
    + "</style>"
    + "</head>"
    + "<body style=\"text-align: center;\">"
    + " <div style=\"margin: 0 auto; width: 80%;\">"
    + "   <h1 style=\"font-weight: bold;\">Verify your email address</h1>"
    + "   <p>Welcome to <strong>NXG-JOB HUB</strong>! To get started, please click the button below to verify your email address.</p>"
    + "   <a href=\"[[URL]]\" style=\"text-decoration: none;\">"
    + "     <button style=\"background-color: #007BFF; color: #fff; font-weight: bold; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer; transition: background-color 0.3s;\">Verify Your Email</button>"
    + "   </a>"
    + " </div>"
    + " <p style=\"margin-top: 70px;\"><strong> This email expires in 24 hrs. If you did not create an account using this address, please ignore it.<strong></p>"
    + " <p>Thanks,</p>"
    + " <p style=\"font-weight: bold;\">The NXG-JOB HUB Team</p>"
    + "</body>"
    + "</html>";



    public static final String JOBPOSTING_NOTIFICATION_CONTENT = "<!DOCTYPE html>"
            + "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:th=\"http://www.thymeleaf.org\">"
            + "<head>"
            + "<style>"
            + "body {"
            + "  font-family: Arial, Helvetica, sans-serif;"
            + "  font-size: 1rem;"
            + "  line-height: 1.6;"
            + "  color: #000;"
            + "}"
            + ".container {"
            + "  width: 80%;"
            + "  margin: 0 auto;"
            + "}"
            + ".button {"
            + "  background-color: #007BFF;"
            + "  color: #fff;"
            + "  font-weight: bold;"
            + "  padding: 10px 20px;"
            + "  border: none;"
            + "  border-radius: 5px;"
            + "  cursor: pointer;"
            + "  transition: background-color 0.3s;"
            + "}"
            + "</style>"
            + "</head>"
            + "<body>"
            + "  <a href=\"[[jobURL]]\" style=\"display: block; height: 100%; width: 100%; text-decoration: none; color: inherit;\">"
            + "    <div class=\"container\">"
            + "      <h1>New Job Posting at NXG-JOB HUB</h1>"
            + "      <p>Dear [[name]],</p>"
            + "      <p>We are excited to inform you about a new job posting that might interest you.</p>"
            + "      <h2>[[job_title]]</h2>"
            + "      <p><strong>Company:</strong> [[company_bio]]</p>"
            + "      <p><strong>Location:</strong> [[job_location]]</p>"
            + "      <p><strong>Job Description:</strong></p>"
            + "      <p>[[job_description]]</p>"
            + "      <p>For more details and to apply, please click the button below.</p>"
            + "      <a href=\"[[jobURL]]\" class=\"button\">Apply Now</a>"
            + "      <p>If you have any questions, please feel free to contact us.</p>"
            + "      <p>Thanks,</p>"
            + "      <p>The NXG-JOB HUB Team</p>"
            + "    </div>"
            + "  </a>"
            + "</body>"
            + "</html>";


    public static final String OAUTH_MAIL_CONTENT = "<html >"
            + "<head>"
            + "<style>"
            + "body {"
            + "  font-family: Arial, Helvetica, sans-serif;"
            + "  font-size: 1rem;"
            + "  line-height: 1.6;"
            + "  color: #000;"
            + "}"
            + "</style>"
            + "</head>"
            + "<body style=\"text-align:justify;\">"
            + "  <h1 style=\"font-weight: bold;\">NXGJOBHUB OAUTH LOGIN DETAILS</h1>"
            + "   <p>Dear [[name]],</p>"
            + "   <p>Please find below your Login Details:</p>"
            + "   <p>Email: [[email]]</p>"
            + "   <p>Password: [[password]]</p>"
            + "   <p style=\"margin-top: 50px;\">If you have any questions, please feel free to contact us.</p>"
            + "   <p>Thanks,</p>"
            + "   <p style=\"font-weight: bold;\">The NXG-JOB HUB Team</p>"
            + "</body>"
            + "</html>";
}
